apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: crane-runner
resources:
  - crane-kubeconfig-generator.yaml
  - crane-export.yaml
  - crane-transform.yaml
  - crane-apply.yaml
  - crane-transfer-pvc.yaml
  - crane-kubectl-scale-down.yaml
  - crane-kustomize-init.yaml
  - kubectl-apply-kustomize.yaml
  - kubectl-apply-files.yaml
  - kustomize-namespace.yaml
