apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: update-gitrepo
  namespace: pipeline-test
spec:
  params:
    - name: src-namespace
      type: string
    - name: src-context
      type: string
    - description: 'git repo to save the resources '
      name: git-remote-url
      type: string
    - description: git user.name
      name: user-name
      type: string
    - description: Git user.email
      name: user-email
      type: string
  tasks:
    - name: export
      params:
        - name: context
          value: $(params.src-context)
        - name: namespace
          value: $(params.src-namespace)
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: crane-export
      workspaces:
        - name: export
          subPath: export
          workspace: shared-data
        - name: kubeconfig
          workspace: kubeconfig
    - name: transform
      runAfter:
        - export
      taskRef:
        kind: ClusterTask
        name: crane-transform
      workspaces:
        - name: export
          subPath: export
          workspace: shared-data
        - name: transform
          subPath: transform
          workspace: shared-data
    - name: apply
      runAfter:
        - transform
      taskRef:
        kind: ClusterTask
        name: crane-apply
      workspaces:
        - name: export
          subPath: export
          workspace: shared-data
        - name: transform
          subPath: transform
          workspace: shared-data
        - name: apply
          subPath: apply
          workspace: shared-data
    - name: kustomize
      params:
        - name: dest-namespace
          value: $(params.src-namespace)
      runAfter:
        - apply
      taskRef:
        kind: ClusterTask
        name: kustomize-namespace
      workspaces:
        - name: apply
          subPath: apply
          workspace: shared-data
        - name: kustomize
          subPath: kustomize
          workspace: shared-data
    - name: git-init-push
      params:
        - name: git-remote-url
          value: $(params.git-remote-url)
        - name: user-name
          value: $(params.user-name)
        - name: user-email
          value: $(params.user-email)
      runAfter:
        - kustomize
      taskRef:
        kind: ClusterTask
        name: git-init-push
      workspaces:
        - name: uninitialized-git-repo
          subPath: kustomize
          workspace: shared-data
    - name: git-clone
      params:
        - name: url
          value: $(params.git-remote-url)
        - name: revision
          value: main
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:afc5d3f9efe26c7042635d43b8ffd09d67936e3d0b6b901dc08a33e20313d361
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: kustomize
          workspace: shared-data
  workspaces:
    - name: shared-data
    - name: kubeconfig

